### ISSUE TITLE
Colors with alpha channel are displayed incorrectly

### ISSUE THREAD

**Issue by flagbug** [abe33/atom-pigments#103]
This image should explain it:

![Pigments](https://cloud.githubusercontent.com/assets/964691/10560414/fc14c20c-750a-11e5-9e04-3df94a5b386e.png)

The second color should be displayed as red, just like the first color

**Comment by abe33** [comment]
AFAIK the only preprocessor that supports hexa rgba notation is Stylus, and it follows the CSS4 draft, which states that 8 digit hexadecimal notation defines a RRGGBBAA color and not a AARRGGBB color. 

https://drafts.csswg.org/css-color/#hex-notation

So this is the proper behaviour regarding CSS.

**Comment by flagbug** [comment]
Ah, that explains the behavior.

I'm using the colors in .NET with XAML, where the colors are expressed as `AARRGGBB`, I thought it's like that everywhere: https://msdn.microsoft.com/en-us/library/bb980062%28VS.95%29.aspx?f=255&MSPPError=-2147217396

Do you think there's an easy way around this?

**Comment by abe33** [comment]
Hmm, interesting, I'm not sure to have a solution out-of-the-box. I'll think about one, probably a setting to switch the format of 8 digit hexadecimal between RGBA and ARGB. Anyway, thanks for the heads up!

**Comment by evilcandybag** [comment]
I have the exact same use case. Would be really great to have the option to set ARGB!

**Comment by DouweM** [comment]
Would it be feasible to have this depend on the scope?

**Comment by abe33** [comment]
@DouweM That might be a really interesting solution thanks for suggesting it! I still haven't found the time to work on that as I'm working on refactoring pigments to allow services to extend the available parser rules, but it's quite a huge change that has impact on a lots of parts in Pigments so I want to focus on it to avoid any drop in performances.

**Comment by DouweM** [comment]
@abe33 Scope-dependent rules sound like a decent use case for the extension framework :)

**Comment by abe33** [comment]
Yes obviously, but that's still a huge feat in itself, I don't even know how I can implement that. There's a lot of the parsing that is made without knowledge of the grammar and scopes - ie. for variables, parsing can occurs on files directly on disk without having a text editor available, and scopes aren't known in this case - so that will probably tough to make it work seamlessly. 

Also, one of the biggest challenge with extension services is that they can be consumed any time - you install a package that contains one I need to take that into account and restart a parsing of all the files in project and all opened editors - I need to make sure these cases are well handled as well as the more general case where every extension are consumed when their package is activated, I need to avoid spending the package initialization to reparse the same files over and over again because the extensions are consumed one after the other.

Anyway, this is a pretty interesting idea, and it sure is tempting to make a part of the parsing system in itself (which would globally reduce the cost of parsing). So I'll keep that in that in mind and look for a good way to solve this (maybe scope could be replaced with an extension to make it work without grammars).
