### ISSUE TITLE
Variables in Sass Syntax not working

### ISSUE THREAD

**Issue by mike3run** [abe33/atom-pigments#106]
It was working then suddenly not.

I tried reload pigments, find variables and even uninstall and reinstall. 😩

![Issue](https://cloud.githubusercontent.com/assets/7088511/10768465/e2bacb50-7ca6-11e5-9968-c2d37f943041.png)

**Comment by abe33** [comment]
Hi @mike3run, thanks for the report but I will need some more information:

1. I would need the classical combo OS version/Atom version/Pigments version.
2. Have you noticed errors popping up in the console? Either at startup or when typing in the editor?
3. Do you still have the same issue after cleaning the data in storage? (see my post on discourse on how clearing the serialized data for a given project: https://discuss.atom.io/t/atom-is-loading-old-version-of-a-file-even-after-a-restart/17432/3)
4.  When typing in the file in question, does the variable are still not recognized?

**Comment by mike3run** [comment]
Hey there, sure:

1. Mac OS X - El Capitán Latest / Atom Latest / Pigments Latest
2. No errors
3. I did clean data. Actually I erased fully the contents of ~/.atom/storage
4. Some color variables are recognized but without the dot of color on them.

I hope I could provide some help

**Comment by abe33** [comment]
Hi @mike3run, sorry for the late reply, would you mind sharing the file in question so that I can take a look a the issue. 

Also, are you able to see the colors defined as variables in the palette view?

Lastly, could you share with me your pigments config and eventually the project config?
For the former you can run `JSON.stringify(atom.config.get('pigments'), null, 2)` in the devtools to get the config object in a nicely formatted JSON. For the later there's no easy way to get an output of the config, but it will matters only if you have changed something in the `Pigments: Project Settings` view.
