### ISSUE TITLE
Improve performances when updating color markers.

### ISSUE THREAD

**Issue by abe33** [abe33/atom-pigments#116]
I'm looking for some way to improve Pigments updates and I would like to gather suggestions about the various strategy available. 

For the use case, there's the [color parser specs](https://github.com/abe33/atom-pigments/blob/master/spec/color-parser-spec.coffee), with Pigments enabled it looks like this: 

![color parser specs](https://cloud.githubusercontent.com/assets/247140/11208644/b0e50f6a-8d1c-11e5-8507-8f2c3bbc0251.png)

On beta, when scrolling in parts of the buffer with a huge marker density, the timeline looks like this: 

![timeline](https://cloud.githubusercontent.com/assets/247140/11208673/d00d3714-8d1c-11e5-85df-f84222bbd7ed.png)

As you can see, the update of the markers takes almost 80ms (sometime even 100ms). 

Currently, I'm using a pool of custom elements that are kept in the DOM and receive a [ColorMarker](https://github.com/abe33/atom-pigments/blob/master/lib/color-marker.coffee) as model during the update (only if when they go from an unused state to a used one) and generates their inner content from that (a bunch of `regions` divs mostly based on the way highlight markers works).

It appears that beyond DOM manipulation inside a color marker view, one costly operation is the computation of the screen coordinates of the underlying buffer markers:

![timeline details](https://cloud.githubusercontent.com/assets/247140/11208939/5820b18e-8d1e-11e5-898b-381a33b41192.png)

I'm also wondering if using a tile-based strategy or a custom marker layer could be of some help here. 

Any thought?

cc/ @nathansobo @as-cii

**Comment by nathansobo** [comment]
@abe33 this seems like a great candidate for a new decoration type, an "inline highlight". If you called `decorateMarker(m, {type: 'highlight', inline: true})`, instead of creating highlight divs that are absolutely positioned *behind* the text, it wraps the marked range in a span element with the desired class (or multiple if the range is multi-line). This would allow you to write inline styles directly on the decoration. It also seems like decorations would need to support a `style` property that you could update in order to control the background and foreground color for that region on an individual basis.

Would you be interested in adding this API? We could coach you through it.

**Comment by abe33** [comment]
Sure, that would be a great addition. 

Actually, I don't use decorations for a few reasons: 
- No decoration can change the text color, and this is mandatory if I want to use a contrasting color over a highlight decoration. Otherwise, depending on the theme, some colors will make the text unreadable.
- Highlight decorations cannot receive custom attributes and don't support the `item` property. In Pigments' case each marker represent a color that is possibly unique, using the `class` property in that case would imply that I must generate a class for every unique color I want to display. Having the ability to specify custom decoration attributes would greatly help in that case.
- I have two color markers type that are positionned at the end of a line: 
 <br/>![](https://github.com/abe33/atom-pigments/raw/master/resources/dot-renderer.png?raw=true)![](https://github.com/abe33/atom-pigments/raw/master/resources/square-dot-renderer.png?raw=true)
  <br/>For these two types it would need another kind of decoration, something like a gutter decoration (supporting the `item` property) but used as a line suffix. Having the decorations positioned relatively so that they can use the natural flow of the line instead of the absolute positioning I use actually would be great.

> Would you be interested in adding this API? We could coach you through it.

Of course! I'll have to take a deeper look at how decorations are rendered, but Pigments is indeed a great candidate for this new type of decoration (and this kind of feature was requested so many times on discuss that I guess I won't be the only one to use it). Actually I probably miss the first steps to implement this (it's late, I just come back from a The Dictators show in Bordeaux so I'm not really in the best conditions to look at Atom sources and find where to start) so I'll probably need some advices and pointers on where to start the work.

**Comment by nathansobo** [comment]
@as-cii actually experimented with an implementation to do this for all highlights in order to save rendering cost, but he abandoned it due to usability issues with interleaved spans when highlights overlap. Opting in to this behavior only when needed however eliminates the usability problems. Not sure if @as-cii has the code, but maybe he could at least describe the approach he had in mind for deciding when to open and close inline highlight spans.

As for the colored circles / squares on the end of lines, could you use overlay decorations for those by chance?

**Comment by abe33** [comment]
> As for the colored circles / squares on the end of lines, could you use overlay decorations for those by chance?

Haven't tried. but overlays decorations are bound to either the marker's head or tail, right? 
So if I want to attach them to the line itself I need to create another marker for the whole line, and then attach an overlay decoration to it with all the dots as its item content. Or maybe I missed something?

**Comment by nathansobo** [comment]
> So if I want to attach them to the line itself I need to create another marker for the whole line, and then attach an overlay decoration to it with all the dots as its item content.

I think you should be able to create a marker on the end of the line. We may need to improve the API if you can't position them quite where you want, but it feels like the proper tool.

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
