### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by powerbreak** [abe33/atom-pigments#123]
![mal](https://cloud.githubusercontent.com/assets/16387598/11941574/eab6bab6-a830-11e5-8048-98809be23ac8.jpg)
So i dont know whats up with this but avast is poping up malware alert. Its probably a false positive but it doesn't appear on any other package i open.

**Comment by abe33** [comment]
I see a `cdn.rawgit.com` in the popup, it looks like avast consider the svg logo as a threat (https://cdn.rawgit.com/abe33/atom-pigments/master/resources/logo.svg for the exact url). I have to use rawgit because github serves raw SVG as plain text, preventing Atom/Chromium from displaying it. But it's just a plain svg image, rawgit only change the mimetype of the server response.

I'm not sure what actions is required to prevent Avast from complaining about that (no longer on windows systems).

FWIW there's a long thread about antivirus triggering false positive with Atom: atom/atom#3927
