### ISSUE TITLE
Color picker shows wrong color in SCSS

### ISSUE THREAD

**Issue by DerNivel** [abe33/atom-pigments#135]
When using something like `transparentize(#fff, .5)` in SCSS the opened color picker shows a wrong color when opened through the color dot.
Maybe you should disable the functionality of opening the color picker through a click on the color dot in these cases or forward the compiled color to the color picker if possible.

**Comment by abe33** [comment]
Haha, nice catch @DerNivel, actually I knew about this issue, I was just curious to see how fast it would be discovered (I had anticipated that by adding a method to know if a color relies on variables or not: https://github.com/abe33/atom-pigments/commit/273f9b298726174852d88be8cf0180a0b1d4222e). 

Ideally I would like the color-picker API to provide a way to let me set the color, so that I can specify the original color, sadly this is not available for the moment, and there's too much differences between how the two packages deal with colors to accurately detect when a color will be parsable by the color picker. I'm still wondering whether I should submit a change in the color-picker API or try to handle that in Pigments.

**Comment by DerNivel** [comment]
Ah ok. Thanks for the information. I updated to the new version and this issue was the first thing that got my attention :smile:

**Comment by abe33** [comment]
Version 0.21.0 now prevents from opening the color picker if the color doesn't isn't a hexadecimal color.

**Comment by DerNivel** [comment]
On things like `transparentize(#fff, .5)` the color picker still opens and shows random colors.
On things like `$main-color` where the color picker doesn't showed a wrong color it doesn't open anymore.

**Comment by abe33** [comment]
Hmm, right I may have been too quick with that, I'll make a patch soon

**Comment by abe33** [comment]
I'll have to wait a bit to go further and let the color picker handle colors where variables are used since it would imply a complex work to check whether a variable holds an expression that can be matched by the color picker. But at least it should no longer open in context where it can't parse the color.
