### ISSUE TITLE
Enchance autocomplete

### ISSUE THREAD

**Issue by dzhiriki** [abe33/atom-pigments#142]
It would be nice if autocomplete show suggestions by variable value, not only by variable name.
For example, i have 2 variables:
```less
@color-black: #000;
@color-white: #fff;
```
and when i start typing `#0` я wanna see suggestion for variable `@color-black`

**Comment by abe33** [comment]
Hi @dzhiriki, interesting suggestion, it would be nice indeed, and I don't think there's much issue to implement something like this. I'll try to look into this when I get some time to works on Pigments.

**Comment by dzhiriki** [comment]
I currently try to implement this. 
But there are some problem to find partial color declaration and parse it correctly. 
If we have only hex we can simply match strings (`#00` and `#000000`). Easy.
But if I type `rgba(255,` we need understand what we need to filter colors only by red-channel. And when we only type `rgba(2` we should find colors with red equal to 2** or 2* or 2.

And i think that it would be awesome if we can implement fuzzy-search (for example, if I type `#4d5666` and project contain variable with `#4d5767` value) – designers often make mistakes in color.

**Comment by abe33** [comment]
Right, seems more complicated than I thought at first. I plan to take some time this week-end to fix travis builds on beta, so I'll take some time to look at this too.

**Comment by mrchimp** [comment]
+1 I was about to suggest this myself. Would be super useful.

**Comment by krjordan** [comment]
Any progress on this? It would definitely save me some time looking up the color variables!

**Comment by abe33** [comment]
I just started working on it, it seems working fine so far (it just supports hexadecimal values actually), I'll have to see how I can actually make it work with any kind of values. As for fuzzy matches, having played a bit with that before, and seeing how autocomplete in Atom works, meaning that suggestions are sorted in block based on a provider priority, and not a per-suggestion priority, it's either you have garbage suggestion on top (fuzzy matches will almost always return something) or suggestions are buried at the of the suggestion list. That's why I had t remove it in the early versions of the package. Maybe there was a change in autocomplete on that front, I'll have to update myself on that.
