### ISSUE TITLE
Option to disable word matching

### ISSUE THREAD

**Issue by code-tree** [abe33/atom-pigments#153]
Is it possible to add an option (or possible already?) to disable matching color words?

e.g. Blue, chocolate, etc

Use case: I never use words to define colors, but would still appreciate matching #hex etc, even in text documents.

**Comment by MasterAscendent** [comment]
I  was coming to ask the same thing. I would love to be able to turn names on/ off where I could make a list of color names and not have it be affected by the addon. Thank you for your wonderful work! :)

**Comment by abe33** [comment]
Hi there, I'm still looking to a simple way to deal with this, as is, it's a bit complicated to exclude a rule or a part of a rule of the whole parsing engine. My first idea was to provide a specific class on decorations with the key of the expression that was matched so that you can hide decorations by source without preventing Pigments to use these colors in the resolution process - let say you don't want to see `blue` highlighted, but it may be affected in a variable that is later used to generate a new color, ignoring completely `blue` would make pigments miss every derived colors - but I hit an issue with the serialized state of the color, so I'll have to update a whole bunch of tests and fixtures to account for that new change.

**Comment by abe33** [comment]
I think the simplest solution right now is to allow these expressions only in css related files (css, sass, etc.) and extends that through a setting. I'll make that available in the next release.

**Comment by code-tree** [comment]
Sounds great, thanks!
