### ISSUE TITLE
Hex color with alpha component rendered incorrectly

### ISSUE THREAD

**Issue by dessant** [abe33/atom-pigments#156]
```
hex('#FF000080') rgba(255, 0, 0, 0.5)
```

![capture](https://cloud.githubusercontent.com/assets/7513068/13535418/bb005524-e242-11e5-9014-780c73036ff6.PNG)

https://drafts.csswg.org/css-color-4/#hex-notation

**Comment by abe33** [comment]
Hi @dessant, in which context are you looking at this expression? By context I mean the type of the file and the grammar applied. I ask that because the CSS version (#RGBA) is supported in CSS files as well as in all supported pre-processor languages (Sass, Less and Stylus) in every other context the version used is the #ARGB one.

**Comment by dessant** [comment]
I have used a python file for the first example, and this one is a css file, with css grammar applied:

![capture](https://cloud.githubusercontent.com/assets/7513068/13551489/7f221dc8-e344-11e5-94f0-a7f5dbad0e9c.PNG)

**Comment by MMayla** [comment]
I have the same issue, I am using it in `.js` file.
