### ISSUE TITLE
same name

### ISSUE THREAD

**Issue by Turqueso** [abe33/atom-pigments#168]
On gradients, if you use the same color name but are focusing the line it won't color the second one. I'm using scss and variables. With name colors and hex works fine.
![image](https://cloud.githubusercontent.com/assets/4932347/14126054/78229728-f5c3-11e5-9ccd-d148eb6d2cd0.png)

When not focusing the line it looks like this
![image](https://cloud.githubusercontent.com/assets/4932347/14126060/7dd42e8e-f5c3-11e5-86fa-9ca5e656c665.png)

The code so you can test
```
$azul-200:        #abced4;
.test {
  background-image: linear-gradient(90deg, transparent 59px, $azul-200 59px, $azul-200 61px, transparent 61px)
}
```

**update**: it started working fine :confused:

**Comment by abe33** [comment]
Hi @Turqueso,  It looks like a glitch when computing the markers position rather than a highlighting issue to me.

Here's on my computer: 
![](https://cloud.githubusercontent.com/assets/247140/14173520/a135da36-f73e-11e5-9d3d-0f4ec5a96962.png)

I'm still fighting with the text editor to get the proper coordinates when editing a file, as there's some uncertainty about the screen position of a marker until the text editor view made its render.

**Comment by C-Bouthoorn** [comment]
As stated in the update it now works fine, so I guess this can be closed?

**Comment by abe33** [comment]
Yeah, I think we can close (based on the update)
