### ISSUE TITLE
Suggestions for both dashes and underscores

### ISSUE THREAD

**Issue by lukereative** [abe33/atom-pigments#171]
When listing autocomplete suggestions for variables (colors or non-color) two suggestions are shown for any variable that has a dash or underscore in it's name, even if only one of them are defined.

I would expect it to only show the variable's (dash or underscore) that you have defined;

![screen shot 2016-04-06 at 12 23 47 pm](https://cloud.githubusercontent.com/assets/1415622/14302196/7a6f886c-fbf2-11e5-9f50-fc5a51ec24f2.png)

**Comment by abe33** [comment]
The thing is that sass allow for the two form whatever the one you used to defined it. And If I want to properly highlight the two versions (which can occurs if there's inconsistencies in the format used across the project) I need to register both version as variables otherwise they won't get highlihghted properly (and could break the evaluation of some other colors if they use the alternate form).

I'll see if I can distinguish between the original and alternate forms in the autocomplete provider, but it'll require to add some new metadata when parsing the variables so I can't give an ETA yet.

**Comment by lukereative** [comment]
Thanks for that explanation. Fortunately it doesn't directly impact the functionality, it just clutters the autocomplete list (especially when you have 4 variables which double to 8 with both variations) and makes it hard to be consistent.
