### ISSUE TITLE
Case Sensitive?

### ISSUE THREAD

**Issue by CassySpencer** [abe33/atom-pigments#177]
Why does this work:
color: rgba(255,0,0,1)

but not this:
color: RGBa(255,0,0,1)

Why does this work:
color: red

but not this:
color: Red

Why do you have to make it case sensitive?  That uses MORE CPU and that's the other big gripe I have with this package.

**Comment by C-Bouthoorn** [comment]
How exactly does case sensitive use more cpu?? It needs 1 check instead of 2??

**Comment by CassySpencer** [comment]
If I need to explain that to you, you need to go back and have your CompSci
degree reevaluated.
Poorly educated people like you make me fear for the next generation.

**Comment by C-Bouthoorn** [comment]
Okay, I'm sorry for asking to get smarter as your next generation.

First of all, I don't have any degree yet, and I'm here to _learn_, that's why I asked.

Second,

*If I'm right,*  checking `'a' == 'a'` takes 1 operation, while `'a'=='a' || 'a'=='A'` takes 2.

Please correct me if I'm wrong there, so I can keep learning.

**Comment by CassySpencer** [comment]
Wow!

**Comment by C-Bouthoorn** [comment]
> Wow!

What's so surprising?

**Comment by abe33** [comment]
@C-Bouthoorn Don't fuel it, it doesn't look like she/he wants to have a constructive discussion here.

While it's true there's an issue with case-sensitivity due to the way Pigments parse colors (using JS regular expressions, which doesn't support local options as other regexes engines, and building a big one with all the supported expressions). There's also a lot of issues to switch the whole thing to use a case-insensitive regex (parsing variables for instance) so I'm still wondering what would be the best course of actions to solve that issue.

Also, about the claim that sensitive regexp are slower that insensitive one, it's just false. Here's a benchmark: https://jsperf.com/case-sensitive-regex-vs-case-insensitive-regex/2

```js
Benchmark.prototype.setup = function() {
    var string1 = 'function name(arg1, arg2) { [native code] }';
    var string2 = 'FUNCTION NAME(arg1, arg2) { [native code] }';
    var sensitive = /function\s?(.*?)(?:\(.*?\))\s?{/;
    var insensitive = /function\s?(.*?)(?:\(.*?\))\s?{/i;
  };
```

And since JSPerf is offline at the moment I'll post the results of the google cached version here:  

![case-sensitive_regex_vs_case-insensitive_regex_ _jsperf](https://cloud.githubusercontent.com/assets/247140/15140905/945dd18c-169d-11e6-8524-8aa03a8addff.png)
![case-sensitive_regex_vs_case-insensitive_regex_ _jsperf](https://cloud.githubusercontent.com/assets/247140/15140922/a3998d4e-169d-11e6-9145-89a5360c4690.png)
