### ISSUE TITLE
Atom Helper uses >100% CPU

### ISSUE THREAD

**Issue by electricarts** [abe33/atom-pigments#190]
With the Pigments package enabled, Atom Helper uses more than 100% CPU. When disabled, CPU usage goes back to 3%. CPU usage changes directly with the Marker Type. With "Dot" and "square-dot" the usage is about 5-7%. Using "background", "outline" or "underline" the usage rise to >100%.

**Comment by Benjamski** [comment]
I absolutely love this package. But after some testing and referencing https://github.com/atom/atom/issues/3426 I'm almost positive pigments is the issue. If there's any data I can provide in order to debug this issue I'm more than happy to help, I'm going to miss such a beautiful package. Between this and Tyler Eich's http://www.packal.org/workflow/colors colors workflow being broken from the update to Alfred 3, I feel like the world is in black and white 😞

**Comment by espensgr** [comment]
I have the same problem, Atom helper uses 100% CPU. When i turn off i goes to around 1%. I have the 0.27.0 version

**Comment by abe33** [comment]
Hi there, please see #125 which already have a discussion about this problem and explanations about what I need to investigate this issue.

I'll close this issue so that we keep the discussion in one place.
