### ISSUE TITLE
Pigments fails to resolve variable colors returned by a SASS function

### ISSUE THREAD

**Issue by yeskunall** [abe33/atom-pigments#207]
Hi! Here's some screenshots for further clarification:

The SASS function is declared in a separate file `_variables.scss` as follows

![variables](https://cloud.githubusercontent.com/assets/14703164/16941371/aa5b4838-4d5d-11e6-8aba-b98bcfab364c.JPG)

Now, when the function is called in another file `some_file.scss`, it seems to fail to resolve the color like it usually does. Here's another screenshot

![new](https://cloud.githubusercontent.com/assets/14703164/16941408/e92532fe-4d5d-11e6-8845-e3ffdc1bc346.JPG)

This problem only seems to occur when a SASS variable (as a color) is returned by the SASS function. It works just fine when called separately, as seen in the screenshot above.

**Comment by abe33** [comment]
Hi there, actually pigments doesn't include a full sass parser, so it cannot evaluate the result of ay sass functions. 

There's many issue at the moment regarding the use of a real sass parser, first, it means bundling extra dependencies, and there's always the issue of the css parser to bundle. Using lib-sass (though node-sass) would make more sense being on a node environment, but the issue is that you can't just parse all sass with it (especially code for sass >=3.4).  And that would also mean doing the same for less, stylus, etc.

What happens in your case, though, because normally it wouldn't just try to put a color next to any function call, is that `color` is a CSS4 function whose support have been added to pigments for postCSS users, I'll make its scope more restrictive so that it doesn't pollute other CSS variants.

**Comment by yeskunall** [comment]
I do see the issue of parsing `SASS` files using `node-sass` and the even greater issue of adding support for other `CSS` pre-processors. :no_mouth:

Thanks a lot for the response, though. :+1:
