### ISSUE TITLE
Please add support for SCSS !default flag

### ISSUE THREAD

**Issue by kotwgarnku** [abe33/atom-pigments#223]
It would be great if pigments reacted to the following SCSS syntax:
```scss
$variable: red;
$variable: green !default;
```
in which case [according to SASS documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_) `$variable` would be still red.

Right now:
![pigments](https://cloud.githubusercontent.com/assets/8173940/18088672/3242d55c-6ebc-11e6-9d1a-57d33ea41913.png)
it can be misleading.

Fix wouldn't require parsing sass, just a simple regex probably.

**Comment by C-Bouthoorn** [comment]
It would require parsing, because what if `$variable: red` wasn't there? Then `$variable` would still be green. What if that `$variable: red` is in a different file? How do we know that that other file is loaded first? I'm afraid that this wouldn't be a simple regex but that it would require quite a bit of parsing.

**Comment by abe33** [comment]
Actually it might not be that hard to implement, Pigments already provides a default mecanism through `.pigments` file. It might just be a matter of generalizing the definition of default variables so that variable expression parsers can set that themselves. Stay tuned

**Comment by abe33** [comment]
![variables-after-mixins_scss_ __users_c_nehemie_github_atom-pigments](https://cloud.githubusercontent.com/assets/247140/18748097/0ee609ea-80d1-11e6-884e-deafb5bf0127.png)
✨
