### ISSUE TITLE
Fix the bad UX between your need to alert and my need to not care.

### ISSUE THREAD

**Issue by envygeeks** [abe33/atom-pigments#23]
I understand your need to alert, I really do... I do not however appreciate the bad alert designs.  It is not ever acceptable to take over and block a users ability to use their software in a non-critical situation and "paths size threshold exceeded" is not a critical message, it's something you could have clearly side alerted about while disabling it for the current session.  Even Atom itself side alerts critical messages it can recover from, why are you not using that UX idea for your UI?

What do you do instead? You block my ability to use my own editor until I pay attention to something that is irrelevant, that's bad design, no matter how you try to justify it, what makes it worse is you do not allow click close on any area so I can rid of it quickly and get work done and no having a button that says "ignore this" is not good UX.

I appreciate the software it's great :+1: , I don't appreciate the bad UX :-1:

**Comment by abe33** [comment]
You're completely right, it was my mistake. I hope to fix that soon by making pigments able to handle thousands of variables without requiring to parse their value every time something change (which is actually the biggest bottleneck). 

I can raise the threshold to say 300 or 500 so that it won't popup unless you're in a really huge project, that would be a temporary measure until I finish working on optimizing the management of the variables collection (currently in cn-variables-collection). What do you think about it?

**Comment by envygeeks** [comment]
@abe33 to fix it in this particular project I ignored the folders causing the issue and sent a pull request to default ignore those folders since they are quite common since Ruby is a popular language like JavaScript (Node/io.js)

**Comment by abe33** [comment]
Yup, I saw your PR, looks good to me, I'll merge it soon. I think I'll raise the threshold too for the time being.
