### ISSUE TITLE
Pigment and the color variable (hex) disappears when the line is selected.

### ISSUE THREAD

**Issue by pingshunhuangalex** [abe33/atom-pigments#321]
Thanks for fixing the package @abe33 

After the update I noticed that:

1. When I select the line where the color lies, the color itself and the hex or Sass variable representing the color will also disappear.
2. Upon selection, the text will be there but the color will not be displayed.

Both issues are reproducible in Atom's default theme, so it's probably not a theme issue.

I'm using the latest Atom 1.19 beta5 (Win 10) with Atom Material theme. Thanks.

![image](https://user-images.githubusercontent.com/17170199/28598552-af1fe7de-71e7-11e7-9eca-704e1ec2638d.png)

![image](https://user-images.githubusercontent.com/17170199/28598559-ba8f4880-71e7-11e7-80e6-4ac0ff5f6ea5.png)

![image](https://user-images.githubusercontent.com/17170199/28598602-0a43c270-71e8-11e7-8124-54eea6e9a043.png)

**Comment by abe33** [comment]
Hi @pingshunhuangalex, interesting.
The expected behaviour should be that the color marker disappears when either a cursor or a selection intersect with the marker, so as to not introduce weird behaviour when editing a color.
But the case of the color disappearing as in your second screenshot is totally new to me. I'm not sure what triggers that as I'm not reproducing it (currently running v1.20.0-dev, but the change was made originally to support v1.19).

If you know how to use the devtools could you inspect the corresponding marker when it gets into the same state as in your second screenshot? To do so you have to start inspecting the whole line then by entering successively in its children you should look for an element with the class `pigments-native-background`. That's our color marker. 

I'm curious to see which style rune is not working properly or which other style is polluting our marker. 

<img width="616" alt="_default_common_scss_ ___development_gsoi_newho_et__theme_sass_ ___development_gsoi_newho_vendor_gsoi_style-framework" src="https://user-images.githubusercontent.com/247140/28662428-6b6d7dd4-72ba-11e7-92eb-9dfdfe609a5a.png">

**Comment by pingshunhuangalex** [comment]
Thanks for the reply @abe33 
It seems like the issue is caused by the `z-index: -2` there. Untoggle that seems to solve the problem, but I'm not sure if that change will break something else. Thanks.
![image](https://user-images.githubusercontent.com/17170199/28662980-67f9c604-72ff-11e7-8d65-a9d92992a39a.png)

**Comment by abe33** [comment]
Nice find! Thank you, actually I don't there's any issue to remove this rule, as it was mostly for the previous implementation which was not using text decoration, and as such had to use some dirty little tricks to get the same result. 
I probably couldn't reproduce it because the theme might have some impact on that issue depending on where it puts background colors and relative positionning. 
I'll publish a patch for that soon.
