### ISSUE TITLE
scroll issues with native-dot

### ISSUE THREAD

**Issue by chrisdrackett** [abe33/atom-pigments#326]
I'm finding some odd scrolling issues when scrolling horizontally when using the native dot style.

Here is an example video: https://cl.ly/0Z2T0B3r1I3R

**Comment by abe33** [comment]
Hi @chrisdrackett, nice catch, actually that's because dot decorations are not really appended to the editor but to the gutter and displayed over the text by a little hack. I'll take a look to see how costly it would be to listen to scrolling again to update the dots, and if the cost is reasonable I'll patch that.

**Comment by MiguelDotL** [comment]
When Using  Native dots/ squares, typing atom is now slowing to a crawl. 10-20 seconds for characters to appear after typing them. could this be related to this fix? in only started happening after i updated atom and pigments-minimap yesterday.

**Comment by Devleaf-IT** [comment]
Same here, dot used to work fine, but after being removed the only options are native-dot and native-square, leading to the same issues as MiguelDotL describes above. Atom 1.19.4 on MacOS Sierra, 2017 MacBook Pro.
