### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by valtido** [abe33/atom-pigments#393]
Would you guys consider the following feature:

As a user when I type: 

`body{
color: #990000;
}`

then Save the file, (or setTimeout on keyup) then the code should convert to the following.

`body{
color: $danger;
}`

Where `$danger` is defined in a separate file within the project folder (excluding node_modules of course).

I would do it myself but my knowledge on atom package development is zero.

**Comment by valtido** [comment]
Also maybe have a flag on the settings to turn this feature on/off or turn on/off at save and/or keyup delay

**Comment by C-Bouthoorn** [comment]
What if there are multiple variables in multiple files with the same value? Should we pick one at random? Should we pick the one in the current file? (If there are multiple in the same file: should we use the first or the last?) I agree it can come in handy at times, but you'll have to be a little more specific on how it should work, before someone can implement it :wink:

**Comment by valtido** [comment]
@C-Bouthoorn  I started the conversation with would you *Consider* it as a feature. If not then so be it :).

But if multiple variables are detected (a it should not be the case as that is bad practice) and even if that is the case I am sure a dropdown can be displayed to list multiple icons. 

As for the additional directories, a config settings with an array of folders/files to ignore is not a hard thing to do or use git ignore for that matter.

Optionally it could be to specify the folder of all sass files to look into.

Lastly. if this was a separate package, maybe the details do not matter as much as it can progressively evolve :)

**Comment by C-Bouthoorn** [comment]
I like the idea of this feature, don't get me wrong. I just think pigments is not the best package to add its functionality to. Pigments is mostly about finding and displaying colours, whereas this idea is about finding and replacing colour variables.

I agree there is quite some overlap, but I'm afraid it would take more effort refactoring on pigments's side than it would be to create a new package for it. Pigments already is [slow](https://github.com/abe33/atom-pigments/issues/351), [limited in support](https://github.com/abe33/atom-pigments/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement), and, frankly, [abandoned](https://github.com/abe33/atom-pigments/commit/c4b7c4a74f3f6fdfdd3137816c7e468fb223bbe0).

A new and fresh package, which provides support for all kinds of different preprocessors, would be the best way to implement this. That's why I'm closing this issue; definitely not because it's a bad idea (I'd love to help implementing it!), but because it's out of scope for pigments.
