### ISSUE TITLE
Not available to download Pigments from Atom Install Packages

### ISSUE THREAD

**Issue by Teveloper** [abe33/atom-pigments#395]
Hi, I tried to download pigments from Atom packages and failed.
Please check if it happens on your side too, and guide me the solution. 
Many thanks in advance.

> Installing “pigments@0.40.2” failed.Hide output…
Unable to download https://www.atom.io/api/packages/pigments/versions/0.40.2/tarball: getaddrinfo EAI_AGAIN www.atom.io:443

> Installing “pigments@0.40.2” failed.Hide output…
Request for package information failed: getaddrinfo EAI_AGAIN atom.io:443 (EAI_AGAIN)

**Comment by C-Bouthoorn** [comment]
It seems you failed to connect to the website of `atom.io`, which is not directly related to pigments. 
This problem seems to be related to https://discuss.atom.io/t/cant-install-packages-from-inside-atom/10971/6 and https://github.com/atom/atom/issues/5148 , which state that there's probably an issue with your DNS server or your proxy.
