### ISSUE TITLE
Pigments returns wrong color highlight output from function

### ISSUE THREAD

**Issue by dawidk92** [abe33/atom-pigments#49]
I'm using shade function to mix color with black:
```sass
@function shade($color, $percentage) {
    @return mix($color, black, $percentage);
}
```

Here's the result:
![zrzut ekranu 2015-07-09 o 17 22 56](https://cloud.githubusercontent.com/assets/7023167/8599156/2dacf262-265f-11e5-9944-74c0c6b5576d.png)
 
It highlights it as black but in fact it's only a little more darken than $color-primary and it's value is equal to #1DBC91

**Comment by abe33** [comment]
Hmm, looks like I forgot to handle percentages without the `%` at the end, I'll try to fix that soon. Thanks for the report!

**Comment by dawidk92** [comment]
I dont know if it should work right now but I updated plugin to v0.8.4 and I have the same problem. It also doesnt work with '%':
![zrzut ekranu 2015-07-10 o 11 35 31](https://cloud.githubusercontent.com/assets/7023167/8615991/dc564172-26f7-11e5-8093-47d9640349af.png)

**Comment by abe33** [comment]
AFAIK there's no default implementation of `shade` and `tint` in sass, the implementation is either a custom one or the one from compass. 
However, Stylus does have `shade` and `tint` functions out of the box, so my implementation is based on the Stylus one (I try to support every major preprocessor features, but I can't support every functions defined in every libs built upon them).
The thing is that, in compass, and as described [here](https://css-tricks.com/snippets/sass/tint-shade-functions/), the percentage argument define the amount of the passed-in color in the resulting color, not the percentage of black/white as Stylus version does. 
As both signature are identical I don't actually have a way to detect which version should be used. It'll suppose that the parser know about the origin buffer scope everytime it have to evaluate a color which is not the case actually. 
So for the moment I don't have a solution, sorry for the inconvenience. I'll try to think of a way to solve that, but it's no small task so I can't really give an ETA for that.

**Comment by robsonsobral** [comment]
Hi!

I saw that `tint`, `shade` work and I gonna ask you for [another custom function](http://erskinedesign.com/blog/friendlier-colour-names-sass-maps/):

```sass
@function palette($palette, $tone: 'base') {
    @return map-get(map-get($palettes, $palette), $tone);
}
```

But you're right. You can't implement everything from every library. I though you could was actually executing the functions.

By the way, the reference you're using for Compass is wrong.

From [Compass](https://github.com/Compass/compass/blob/d5df161d0df7edc686e576b22412f437dd0590cc/core/lib/compass/core/sass_extensions/functions/colors.rb):

```ruby
  def tint(color, percentage)
    assert_type color, :Color
    assert_type percentage, :Number
    white = rgb_color(255, 255, 255)
    mix(white, color, percentage)
  end
```

From [Sass Guidelines](http://sass-guidelin.es/#lightening-and-darkening-colors):

```sass
/// Slightly lighten a color
/// @access public
/// @param {Color} $color - color to tint
/// @param {Number} $percentage - percentage of `$color` in returned color
/// @return {Color}
@function tint($color, $percentage) {
  @return mix(white, $color, $percentage);
}
```

So, it looks like `tint` and `shade` match the Stylus behavior.

**Comment by abe33** [comment]
@robsonsobral I'm currently working on making Pigments extensible through a service so I'll think on how you can implement your palette method (not sure since you're using a map and I don't support them for the moment).

>  I though you could was actually executing the functions.

Nah, too complex. First problem is that it would require to ship Pigments with all pre-processors, or to know how to find which pre-processor is used. It would also require to know how to setup the pre-processor: if compass is used, how do I find where compass is installed, what if the project uses bourbon instead, what if it uses libsass and not ruby sass, it's endless.

> So, it looks like tint and shade match the Stylus behavior.

I'm not sure about that, these two methods, when implemented in sass, are relying on the `mix` function, which is [implemented in Pigments](https://github.com/abe33/atom-pigments/blob/master/spec/color-parser-spec.coffee#L394-L419) and works as described in the [sass documentation](http://sass-lang.com/documentation/Sass/Script/Functions.html#mix-instance_method). But you're right the output color for tint and shade doesn't match what should be the result (as described [here](https://css-tricks.com/snippets/sass/tint-shade-functions/)) so I'm a bit at loss here. 
I'll have to dig further in the various implementations to find out why it differs. Hopefully, I'm implementing a feature that will allow to use different expressions based on the file extension, so I should be able to make the shade and tint expressions behave differently in sass and stylus/less files.

**Comment by abe33** [comment]
Ok, I should have read my previous comment, as I already found out about the difference. I should be able to fix that then.

**Comment by robsonsobral** [comment]
I should have read my comment too.

> I though you could was actually executing the functions.

WTH that was supposed to mean? I'm sorry!

---

Yeah, I'm thing about to use maps for colors, but Pigments is so cool that I can't live without it.

Thanks, @abe33 !

**Comment by abe33** [comment]
Actually I do use maps a lot, but I also generally defines my palette with variables first, then build a palette as a map to ease the generation of classes like `btn-primary`, `btn-danger`, etc.

I've implemented something similar to support Stylus' hash, but sass maps are much more complicated as you have to use specific methods to access their content (while in Stylus you can just use something like `hash.property`). I'll try a few things to see if it can be implemented easily or not.

**Comment by robsonsobral** [comment]
I agree. The `map-get()` is too complex. I tried to use something link `$gray-#{$tone}`, but it doesn't work.

Thank you, @abe33 .
