### ISSUE TITLE
Not installable at the moment?

### ISSUE THREAD

**Issue by saschalalala** [abe33/atom-pigments#54]
Hi, I am running Atom 1.0.2 and tried to install that package via settings and via apm, settings don't find it, apm says:

Request for package information failed: Application error

**Comment by juliancoleman** [comment]
Leaves a pretty nasty hang as well. I've had to disable it for now, but this looks like an amazing package.

**Comment by abe33** [comment]
This is likely an issue with `apm` itself, the `Application Error` looks like the Heroku's standard failure page. Pigments is using nothing fancy, no native module that need to be compiled so I don't see why the install would fail for any other reason than a server issue when downloading the package's asar file. Let me know if you still have this error.

**Comment by juliancoleman** [comment]
Looks like my issue suddenly resolved itself. As you were saying, it was likely an issue with `apm`. Atom did hang for a minute, but it didn't subsequently crash and fail to re-open this time. Looking forward to using this. I've really been needing something like this since switching over from Sublime.

**Comment by abe33** [comment]
Ok thanks for the feedback, I close this issue then.

**Comment by saschalalala** [comment]
Just for your information, I could install it now, too and it works fine. Thanks.
