### ISSUE TITLE
Disable by filetype or regex?

### ISSUE THREAD

**Issue by bronson** [abe33/atom-pigments#57]
As interesting as it is to give each pull request its own color, I find it rather distracting.  :)

<img width="955" alt="screen shot 2015-07-21 at 1 35 32 pm" src="https://cloud.githubusercontent.com/assets/1776/8811841/70f22fd6-2fad-11e5-9595-dcb55d833d5c.png">

Ideally I'd like to disable pigments unless the hex value is surrounded by whitespace (and maybe a leading colon is ok).

Or, maybe I can restrict pigments only to css/less files?

**Comment by abe33** [comment]
Hi @bronson, you can already excludes markers with the `Ignored Scopes` setting, it takes an array of regex to match agaisnt the scope string of the marker (actually the scope at the first position of the marker).
For example I use the following value to ignore colors in comments, markdown files and scss strings: 

```
\.comment, \.source\.gfm, \.scss.*\.string
```

To restrict colors to only css and less files you can try something like that: 

```
^(?!\.source\.css).*
```
It basically ignores all scopes that doesn't start with `.source.css`, so it should only display colors in less, css and scss files.

I also have in my todo to test a version with CSS selectors instead of regexes but I still haven't found the time to work on that.

I'll close that issue since it's already implemented :)

**Comment by andrelima** [comment]
This is not working for me — at least in the latest version.

I have this in config.cson:
```
  pigments:
    ignoredScopes: [
      "^(?!\\.source\\.css).*"
      "\\.comment"
      "\\.scss.*\\.string"
    ]
```

...but still, in Markdown files, words that mention possible colors (like `silver`) get colorized.

**Comment by abe33** [comment]
@andrelima: Actually there's no expressions in your ignored scopes that matches a markdown buffer, as it uses the `.source.gfm` scope, hence the `\.source\.gfm` in my example above.

**Comment by andrelima** [comment]
@abe33: Oh, shouldn't this one apply:

```
^(?!\.source\.css).*
```

...?

**Comment by andrelima** [comment]
...I have to refresh my memory on some of the regex stuff, but that text was based on what you've said before: 

> To restrict colors to only css and less files you can try something like that:
> 
> ```
> ^(?!\.source\.css).*
> ```

**Comment by abe33** [comment]
Oh right, my bad, you're indeed right there's a problem here. I'll take a look at that.

**Comment by andrelima** [comment]
Working now! :) Thank you!
