### ISSUE TITLE
Pigments disappear under cursor

### ISSUE THREAD

**Issue by eboracus** [abe33/atom-pigments#65]
Pigments currently disappear when the cursor is on them. Would it be better if they only disappeared/changed when the value is altered?

![pigments_vanish_on_cursor](https://cloud.githubusercontent.com/assets/11758299/9026361/91234490-3924-11e5-92e5-cc8aeba82223.gif)

**Comment by abe33** [comment]
I made it that way because as these are not native decorations they're displayed above the text editor's content, which hides the cursor when it's positioned in the marker.
Also, the way markers works they'll be destroyed as soon as you touch their content. 
What I can do, though, is to append a class to the marker view instead modifying its display property. That way you can override this behavior using css only.

**Comment by mrmckeb** [comment]
Good idea, @abe33. That'd be a nice addition.
