### ISSUE TITLE
Incorrect Find Colors results font

### ISSUE THREAD

**Issue by defeed** [abe33/atom-pigments#78]
Pigments doesn't display search results with the Atom's theme font.
On a screenshot below, the results font should be 'Consolas'

<img width="1792" alt="screen shot 2015-08-21 at 20 42 54" src="https://cloud.githubusercontent.com/assets/497537/9409493/3e80ea78-4845-11e5-98ad-7df786dd4d11.png">

**Comment by abe33** [comment]
Thanks for the report, I'll try to find how to retrieve the font, but I think it'll be tough. One of the limitation is that the `find-and-replace` package is activated only when you perform a search, so that mean that if you use the pigments search first the `find-and-replace` stylesheet aren't loaded yet. I'll try to see how I can force the activation.
