### ISSUE TITLE
Resolving SASS colors is not restricted to current project folder

### ISSUE THREAD

**Issue by derwaldgeist** [abe33/atom-pigments#79]
I'm using bootstrap in two different projects, hence they are using the same SASS variable names. I noticed that if I open both project root folders in Atom, only one of the project's SASS files show the right colors (e.g. for $brand-primary). Obviously, the parser always scans *all* project directories to determine the colors, and thus finds the same color values for both projects, although they actually differ. I would expect the resolution process to scan the current project folder only, i.e. all files under the root folder where the current file is located in.

**Comment by abe33** [comment]
Hmm, I'm not sure to exactly get what you encounter, can you show me what differs between the two projects? Is there some kind of default override in these projects?

**Comment by derwaldgeist** [comment]
@abe33: Thanks for coming back to me.

Let me explain a bit further: There is a SASS variable named $brand-primary in the SASS version of Twitter Bootstrap. This variable holds the primary color used in the website, i.e. it's "brand color". Of course, this color differs between projects, since every customer an own brand color. So, also the $brand-color variable will differ between projects.

If I open only one of my web site projects in Atom, colors derived from $brand-primary will show up correctly in this project. However, if I have two such project folders open at the same time, it can happen that the colors in project A show the colors of project B. It seems as if the resolution of SASS variables runs over all files, across all projects. So the values of color variables in project B overwrite the values in project A (not really the values, but the colors the atom-pigments will show for the variables derived from $brand-primary).

To make it even more precise:

Project A: colors.scss
$brand-primary: red;
$derived-color: lighten($brand-primary, 30%);

Project B: colors.scss
$brand-primary: blue;
$derived-color: lighten($brand-primary, 30%);

=> It can happen that $derived-color in project A is highlighted in light blue instead of light red.

**Comment by abe33** [comment]
Oh! RIght, I see, I wasn't thinking about multiple roots projects. Thanks for taking time to explain it to me!

Yeah you're right there's a problem here. As I still have to put a strategy in place for priorizing and filtering the variables, they are still priorized using the discovery order (newest variables overrides oldest ones). 
The good news is that in your example above a `$brand-primary` variable with the value `red` still exist in pigments internal representation so I'll be able to change the color evaluation context (which variables holds which value) at the buffer level. 
But things gets tricky when I think about all the possible cases of mutiple roots usage. 
In your example each root directories is a project in itself (with its own color theme) so the best course would be to filter variables by directory. 
But I also know a lot of devs (included myself) that uses multiple roots to link and work on dependencies in a given project, so in that context it makes more sense to group the variables from all the roots as one context (i.e. if I have a root A that contains my sass defaults and a root B that contains A's extensions I would expect the variables from A to be used when evaluating colors in B).

I think this specific use case could be handled through a config to either filter or priorize by root, but there's also the case of `!default` variables that could breaks the per root priorization, or the fact that the current file should always have the highest priority, and I think there's many more cases I haven't thought about.

I can't promise it'll be solved in a really near future but I think it'll be the next thing I'll tackle after finishing the feature I'm working on currently: including Atom themes variables in the context for devs working on Atom packages and supporting a special file for defaults when the colors at the root of the variables tree can't be parsed by pigments (because they are defined by an interpolation from a template language or because they use complex computation not supported in pigments yet). 
In a way it's related as it will require to introduce some kind of ordering so it'll be a good opportunity to think about this problem and the various solutions to provide.

**Comment by derwaldgeist** [comment]
Thanks for fixing this!
