### ISSUE TITLE
Switching from square to dot does not work

### ISSUE THREAD

**Issue by rugk** [abe33/atom-pigments#80]
When switching from square to dot the icons still display the squares:
![pigmentscolorswitcherror](https://cloud.githubusercontent.com/assets/11966684/9528490/f75342c2-4cf4-11e5-8049-18d7fc067c83.gif)

**Comment by abe33** [comment]
Thanks for the report, I may have missed something. I'll take a look at that soon.

**Comment by rugk** [comment]
Just saw in my own gif that curiously the last colour at the bottom changed correctly to a circle.

**Comment by abe33** [comment]
> Just saw in my own gif that curiously the last colour at the bottom changed correctly to a circle.

Yes, I saw that too, and there's a good reason. Actually I reuse a pool of custom elements to display the markers, so when you scroll in a file the markers that are no longer visible got released and can be reused to display the newly visible ones. As they receive a new model they update themselves based on the current settings, so that explain why in that case the newly visible marker was properly rendered. The bug probably comes from an update not passed to the displayed markers when the settings change, 

I'll need to investigate a bit because I was pretty sure to have covered all the cases, but it seems I was overconfident.
