### ISSUE TITLE
Pigments and atom load time

### ISSUE THREAD

**Issue by steveoh** [abe33/atom-pigments#83]
pigments is taking over 10 seconds to activate when I load atom. I was reading a little through #43 and I'm curious what sort of scanning are you doing. I would expect scanning to only take place on the active tab/buffer.

this is on windows with atom 1.10

**Comment by abe33** [comment]
Actually, pigments scans the sources for files that match the `pigments.souceNames` settings. This scanning is done asynchronously so it doesn't impact activation time (it starts after the activation). Its purpose is to list all the variables in the project so that colors can be evaluated even when they reference a variable that comes from a different file.

> pigments is taking over 10 seconds to activate when I load atom.

It may be due to the deserialization of the state. Depending how big your project is, the amount of serialized data can vary, as pigments serialize the project's variables as well as the opened buffers states. But to really understand what's going on in your case I'll need more information.

**Comment by joepaolicelli** [comment]
This is also happening for me. Here is what timecop shows:
<img width="347" alt="pigments load time timecop" src="https://cloud.githubusercontent.com/assets/5841125/10384650/c9132f60-6e0c-11e5-8140-be436779a489.png">

Project size is probably the issue here - I have three project folders, each with a large number of files in nested folders. This doesn't cause me any issues - except, it seems, for Pigments making the load time 16 seconds (as opposed to less than 2 seconds when I disabled Pigments).

I'm using Windows 10, Atom 1.0.19, and Pigments 0.15.0.

**Comment by abe33** [comment]
Would you mind running Atom with `atom --profile-startup` and share with me the resulting profile? As I said in my comment above, without proper informations it's hard to define where the bottleneck is.

**Comment by steveoh** [comment]
`atom --profile-startup` doesn't work anymore. I tried it on windows and osx.I run that command, atom opens, i open the dev tools and click on profiles and nothing is there. Any help @abe33?

**Comment by abe33** [comment]
@steveoh Did you notice anything particular in the resulting profile? Also it may happen than even with the `--profile-startup` option the profiling won't start, in that case, reloading Atom may help getting the proper profiling.

Also, in my own exploration I found I was evaluating all serialized colors on restoration, which was costing a log as it's a synchronous operation. I believe the latest version should perform better. Can you confirm it?

**Comment by intellix** [comment]
400ms here on a MBP

**Comment by PavSidhu** [comment]
Thought I'd reopen this issue since it still seems to be a problem. The startup time on Atom for me is 2311ms. Any reason why this is?
