### ISSUE TITLE
HSB Support

### ISSUE THREAD

**Issue by SavePointSam** [abe33/atom-pigments#85]
Our team uses HSB to define colors. Any chance of this package getting support for it? Thanks!

**Comment by ChristophLabacher** [comment]
I have got the same problem with HSL

**Comment by abe33** [comment]
@SavePointSam: Sure, I'll add that soon, I just need to check how this colorspace works and to write the tests for it.

@ChristophLabacher: What's your problem with HSL? Can you open a new issue with reproduction steps? Because [HSL is actually supported](https://github.com/abe33/atom-pigments/blob/master/spec/color-parser-spec.coffee#L116-L141).

**Comment by ChristophLabacher** [comment]
@abe33 I think I just found my problem: I was writing
```
hsl(20,70,60);
```
instead of
```
hsl(20,70%,60%);
```

Now it’s working. According to the specification you have to use the %, so basically your code is right. My colors were working in all major browsers though, so maybe you might want to consider supporting that version too.

Sorry for the hassle and thanks for you awesome package!

**Comment by abe33** [comment]
@ChristophLabacher thanks for the follow up, it makes sense to also support a version without % as there's a high probability that some pre-processor also support it (I think sass is, I'll have to confirm that though).

**Comment by SavePointSam** [comment]
Please support without %. We wrote out a Sass function that requires colors to look like this, 
`$grey-100: hsb(0, 0, 100);`
