### ISSUE TITLE
Ability to extend pigments

### ISSUE THREAD

**Issue by wyozi** [abe33/atom-pigments#91]
Hi. I created a plugin to extend atom-color-highlight a while ago and now I'd like to convert it to pigments. Is there a guide or simple way to do it like there was with the atom-color-highlight package.

For what it's worth, I'm trying to highlight at least the following expression (in .lua files)
```Color(255, 0, 0, 255) --rgba```

**Comment by abe33** [comment]
Hi @wyozi, initially I wanted to have a pigments service so that packages can register their own expressions, but I faced some difficulties as most of the color parsing is done off the main thread in a task, and expressions that would have been registered using the services wasn't available in the tasks threads. I still have to find a way to consume services so that the tasks threads cann access them. 
In the meantime, you can open a PR to enable support for lua colors, I'll gladly merge it.
